[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"


[project]
name = "solver"
version = "1.0.0"
description = "A minimal MILP solver microservice for Fuku's scheduling engine"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.133.1",
    "ortools>=9.15.6755",
    "pydantic>=2.12.5",
    "uvicorn>=0.41.0",
]

[tool.setuptools.packages.find]
where = ["src"]
include = ["*"]

[dependency-groups]
dev = [
    "jupyter>=1.1.1",
]
